#!/usr/bin/env python2

APP_NAME = "Saved Places Importer"

LIST_STARRED_PLACES = "LIST_STARRED_PLACES"
LIST_WANT_TO_GO = "LIST_WANT_TO_GO"

ADD_FEATURE_SUCCESS = 0
ADD_FEATURE_FAILURE = 1
ADD_FEATURE_ALREADY_ADDED = 2
ADD_FEATURE_UNKNOWN_ERROR = 3

MODE_GPX = "GPX"
MODE_GEO_JSON = "GEO_JSON"
MODE_BATCH = "BATCH"
MODE_INTERACTIVE = "INTERACTIVE"
