#!/usr/bin/env python2

LIST_STARRED_PLACES = "LIST_STARRED_PLACES"
LIST_WANT_TO_GO = "LIST_WANT_TO_GO"

ADD_FEATURE_SUCCESS = 0
ADD_FEATURE_FAILURE = 1
ADD_FEATURE_ALREADY_ADDED = 2
ADD_FEATURE_UNKNOWN_ERROR = 3
